"""update Merchant table

Revision ID: 04e25dbc6d70
Revises: f18b4a995c59
Create Date: 2023-10-21 15:16:47.639445

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04e25dbc6d70'
down_revision = 'f18b4a995c59'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
