"""update Merchant table

Revision ID: 285b10feafb4
Revises: 04e25dbc6d70
Create Date: 2023-10-21 15:22:15.968726

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '285b10feafb4'
down_revision = '04e25dbc6d70'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
