"""update Merchant table

Revision ID: 7e51e00fdb85
Revises: 285b10feafb4
Create Date: 2023-10-21 15:22:37.851520

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e51e00fdb85'
down_revision = '285b10feafb4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
